services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    aintreallydown\DocumentBundle\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/DocumentBundle.php'
            - '../src/Entity/'
twig:
    paths:
        '%kernel.project_dir%/vendor/aintreallydown/document-bundle/templates': DocumentBundle