services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    aintreallydown\DocumentBundle\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/DocumentBundle.php'
            - '../src/Entity/'